spring:
  cloud:
    stream:
      defaultBinder: rabbit
      rabbit: #connection part
        binder:
          admin-addresses: localhost:5672

      bindings: #channels set in binder
        input: #channel name
          binder: rabbit
          destination: stocks-exchange #topic or exchange

        expectedErrorsQueue:
          binder: rabbit
          destination: errors


